INSERT INTO auto_body_styles (name, description) VALUES ('convertible', 'Sleek sporty alternatives: top down or up.')
INSERT INTO auto_body_styles (name, description) VALUES ('coupe', 'Fixed roof, two doors, and a sloping rear.')
INSERT INTO auto_body_styles (name, description) VALUES ('hatchback', 'A car with a door across the full width at the back end that upens upward to provide easy access for loading.')
INSERT INTO auto_body_styles (name, description) VALUES ('minivan', 'A small van, typically one fitted with seats in the back for passengers.')
INSERT INTO auto_body_styles (name, description) VALUES ('pickup truck', 'A small truck with an enclosed cab and open back.')
INSERT INTO auto_body_styles (name, description) VALUES ('sedan', 'An automobile having a closed body and a closed trunk separated from the part in which the driver and passengers sit.')
INSERT INTO auto_body_styles (name, description) VALUES ('sport-utility vehicle', 'A high-performance four-wheel-drive vehicle.')
INSERT INTO auto_body_styles (name, description) VALUES ('sports car', 'A low-built car designed for performance at high speeds.')
INSERT INTO auto_body_styles (name, description) VALUES ('station wagon', 'A car with longer body than usual, incorporating a large carrying area behind the seats and having an extra door at the rear for easy loading.')
